name: "CI"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # unit tests
  tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm test
      - uses: peter-evans/create-pull-request@v5
        with:
          branch: production-promotion

